# Default values for app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: "customer-b"


image:
  repository: hello
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

labels:
  customer: B
  app: hello-app-b

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "customer-b"

service:
  type: NodePort #LoadBalancer # NodePort #ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi