# Default values for app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hello
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

service:
  type: ClusterIP #LoadBalancer # NodePort #ClusterIP
  port: 80

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi