apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ include "app-chart.fullname" . | quote}} #{{ .Release.Namespace | quote }}
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  template:
    metadata:
      labels:        
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "app-chart.fullname" . }}
          env:
          - name: CUSTOMER_NAME
            value: {{ .Values.labels.customer }}        
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}        
          ports:
            - name: http
              containerPort: 80
              protocol: TCP        
          {{- include "app-chart.probes" . | nindent 10 }}         
          resources:
            {{- toYaml .Values.resources | nindent 12 }}