apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- range $name, $value := .Values.labels }}
    {{ $name }}: {{ $value }}
{{- end -}}
{{- include "app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- range $name, $value := .Values.labels }}
    {{ $name }}: {{ $value }}
{{- end -}}
{{- include "app-chart.labels" . | nindent 4 }}
