name: Challenge Jobs

on: [push]

env:
  IMAGE_NAME: hello
  IMAGE_TAG: v1

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_REPOSITORY }}    

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: app
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          # outputs: type=docker,dest=/tmp/${{ env.IMAGE_NAME }}.tar
          push: true
      # - 
      #   name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ env.IMAGE_NAME }}
      #     path: /tmp/${{ env.IMAGE_NAME }}.tar

  # use:
  #   runs-on: ubuntu-latest
  #   needs: build_and_push
  #   steps:
  #     - 
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - 
  #       name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: ${{ env.IMAGE_NAME }}
  #         path: /tmp
  #     - 
  #       name: Load Docker image
  #       run: |
  #         docker load --input /tmp/${{ env.IMAGE_NAME }}.tar
  #         docker image ls -a

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - 
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - 
        name: Check cluster nodes
        run: kubectl get nodes
