name: Challenge Jobs

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: hello
  IMAGE_TAG: v1  

jobs:
  build_and_push:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: iamdempa
          password: ${{ secrets.TOKEN_REPOSITORY }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  container-test-job:
    needs: build_and_push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iamdempa/challenge/hello:v1
      env:
        CUSTOMER_NAME: A
      ports:
        - 80
      options: --cpus 1
    steps:
      - name: Test
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - 
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - 
        name: Check cluster nodes
        run: kubectl get nodes