name: Challenge Jobs

on: [push]

# env:
#   IMAGE_NAME: hello
#   IMAGE_TAG: v1

# jobs:

#   build_and_push:
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         name: Checkout code
#         uses: actions/checkout@v2

#       - 
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       -
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.TOKEN_REPOSITORY }}   

#       -
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: app
#           push: true
#           tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


#   deploy:
#     runs-on: ubuntu-latest
#     needs: build_and_push
#     steps:
#       - 
#         uses: debianmaster/actions-k3s@master
#         id: k3s
#         with:
#           version: 'latest'
#       - 
#         name: Check cluster nodes
#         run: kubectl get nodes


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com #ghcr.io
          repository: iamdempa/test
          username: iamdempa
          password: ${{ secrets.TOKEN_REPOSITORY }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: app
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0